std = {
    globals = {
        "assert",
        "data",
        "defines", 
        "game", 
        "log", 
        "math",
        "pairs",
        "prototypes",
        "require",
        "script", 
        "serpent",
        "settings",
        "storage", 
        "string",
        "table_size",
        "table",
        "tonumber",
        "type",
    },
 }
