return {
	["iron-ore"]="Iron ore", -- base game
	["coal"]="Coal", -- base game
	["copper-ore"]="Copper ore", -- base game
	["uranium-ore"]="Uranium ore", -- base game
	["stone"]="Stone", -- base game
	["crude-oil"]="Crude oil", -- base game
	-- infinite version of base game ores
	["infinite-iron-ore"]="Iron ore",
	["infinite-coal"]="Coal",
	["infinite-copper-ore"]="Copper ore",
	["infinite-uranium-ore"]="Uranium ore",
	["infinite-stone"]="Stone",

	-- Bob ores
	["tin-ore"]="Tin ore",
	["infinite-tin-ore"]="Tin ore",
	["gold-ore"]="Gold ore",
	["infinite-gold-ore"]="Gold ore",
	["bauxite-ore"]="Aluminium ore",
	["infinite-bauxite-ore"]="Aluminium ore",
	["lead-ore"]="Lead ore",
	["infinite-lead-ore"]="Lead ore",
	["quartz"]="Silicon ore",
	["infinite-quartz"]="Silicon ore",
	["rutile-ore"]="Titanium ore",
	["infinite-rutile-ore"]="Titanium ore",
	["tungsten-ore"]="Tungsten ore",
	["infinite-tungsten-ore"]="Tungsten ore",
	["zinc-ore"]="Zinc ore",
	["infinite-zinc-ore"]="Zinc ore",
	["nickel-ore"]="Nickel ore",
	["infinite-nickel-ore"]="Nickel ore",
	["gem-ore"]="Gem ore",
	["infinite-gem-ore"]="Gem ore",
	["sulfur"]="Sulfur",
	["infinite-sulfur"]="Sulfur",
	["silver-ore"]="Silver ore",
	["infinite-silver-ore"]="Silver ore",
	["cobalt-ore"]="Cobalt ore",
	["infinite-cobalt-ore"]="Cobalt ore",
	["thorium-ore"]="Thorium ore",
	["infinite-thorium-ore"]="Thorium ore",
	["ground-water"]="Ground water",
	["lithia-water"]="Lithia water",

	-- Uranium Power
	["uraninite"]="Uraninite",
	["infinite-uraninite"]="Uraninite",
	["fluorite"]="Fluorite",
	["infinite-fluorite"]="Fluorite",

	["tenemut"]="Tenemut cluster",
	["infinite-tenemut"]="Tenemut cluster",

	-- Yuoki
	["y-res1"]="N4-material chunk",
	["infinite-y-res1"]="N4-material chunk",
	["y-res2"]="F7-material chunk",
	["infinite-y-res2"]="F7-material chunk",

	-- Angels
	["angels-ore1"]="Saphirite",
	["infinite-angels-ore1"]="Saphirite",
	["angels-ore2"]="Jivolite",
	["infinite-angels-ore2"]="Jivolite",
	["angels-ore3"]="Stiratite",
	["infinite-angels-ore3"]="Stiratite",
	["angels-ore4"]="Crotinnium",
	["infinite-angels-ore4"]="Crotinnium",
	["angels-ore5"]="Rubyte",
	["infinite-angels-ore5"]="Rubyte",
	["angels-ore6"]="Bobmonium",
	["infinite-angels-ore6"]="Bobmonium",
	["angels-natural-gas"]="Natural gas",
	["angels-fissure"]="Fissure",

	-- PY
	["borax"]="Borax",
	["infinite-borax"]="Borax",
	["niobium"]="Niobium",
	["infinite-niobium"]="Niobium",
	["molybdenum-ore"]="Molybdenum",
	["infinite-molybdenum-ore"]="Molybdenum",
	["ore-quartz"]="Quartz",
	["infinite-ore-quartz"]="Quartz",
	["raw-coal"]="Raw coal",
	["infinite-raw-coal"]="Raw coal",
	["ore-aluminium"]="Aluminium",
	["infinite-ore-aluminium"]="Aluminium",
	["ore-chromium"]="Chromium",
	["infinite-ore-chromium"]="Chromium",
	["ore-lead"]="Lead",
	["infinite-ore-lead"]="Lead",
	["ore-nickel"]="Nickel",
	["infinite-ore-nickel"]="Nickel",
	["ore-tin"]="Tin",
	["infinite-ore-tin"]="Tin",
	["infinite-ore-titanium"]="Titanium",
	["ore-titanium"]="Titanium",
	["ore-zinc"]="Zinc",
	["infinite-ore-zinc"]="Zinc",
	["oil-sand"]="Oil sand",
	["infinite-oil-sand"]="Oil sand",
}
